# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('label', models.CharField(max_length=150)),
                ('field_type', models.CharField(choices=[('t', 'Text'), ('i', 'Integer'), ('b', 'Boolean (Yes/No)'), ('s', 'Dropdown Choices'), ('d', 'Date')], default='t', max_length=1)),
                ('default_value', models.CharField(blank=True, help_text='You may leave blank. For Boolean use True or False', max_length=5000)),
                ('is_required', models.BooleanField(default=False)),
                ('field_choices', models.CharField(blank=True, help_text='List the choices you want displayed, seperated by commas. This is only valid for Dropdown, Multiple, and Checkbox field types', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='riskfield',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_model.RiskType'),
        ),
        migrations.AlterUniqueTogether(
            name='riskfield',
            unique_together=set([('name', 'risk_type')]),
        ),
    ]
